pipeline:
  identifier: Build_cnsivakumar_mydotnetcoreapp_1767860089816
  name: testdotnet
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: cnsivakumar/mydotnetcoreapp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: verify_repo
                  name: Verify Repo
                  spec:
                    image: mcr.microsoft.com/dotnet/sdk:8.0
                    shell: Sh
                    command: |
                      echo "Listing repo contents"
                      ls -la
                  type: Run
              - step:
                  type: Run
                  name: Build and Publish DotNet
                  identifier: build_publish
                  spec:
                    image: mcr.microsoft.com/dotnet/sdk:8.0
                    shell: Sh
                    command: |
                      dotnet --version

                      dotnet restore
                      dotnet build -c Release --no-restore
                      dotnet publish -c Release -o publish --no-build
              - step:
                  type: Run
                  name: Zip Build Output
                  identifier: zip_build
                  spec:
                    image: mcr.microsoft.com/dotnet/sdk:8.0
                    shell: Sh
                    command: |
                      apt-get update
                      apt-get install -y zip
                      cd publish
                      zip -r dotnet-app.zip .
              - step:
                  type: Run
                  name: Upload ZIP to Azure Artifacts
                  identifier: upload_azure_artifact
                  spec:
                    image: mcr.microsoft.com/azure-cli
                    shell: Sh
                    command: |
                      az extension add --name azure-devops
                      az devops configure --defaults \
                        organization=https://dev.azure.com/sivani12 \
                        project=mydotnetapp
                      echo "<+secrets.getValue('AZURE_DEVOPS_PAT')>" | az devops login
                      az artifacts universal publish \
                        --organization https://dev.azure.com/sivani12 \
                        --project mydotnetapp \
                        --feed testharness \
                        --name dotnet-app \
                        --version 1.0.<+pipeline.sequenceId> \
                        --path publish
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
