name: Deploy Azure Web Container using Github actions

on:
  pull_request:
    branches: main
    
env:
  AZURE_WEB_APP: 'dockerzwebapp1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.MYACR }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_SECRET }}
          
       - run: |
          docker build . -t '${{ secrets.MYACR}}/myapp:latest'
          docker push '${{ secrets.MYACR }}/myapp:latest'
       
       - uses: azure/webapps-deploy@v2
         with:
          app-name: ${{ env.AZURE_WEB_APP }}
          images: '${{ secrets.MYACR }}/myapp:latest'
          
          
